### ISSUE TITLE
Gen 3 middleware pipeline for wep

### ISSUE THREAD

**Issue by jbkalmbach** [lsst-ts/ts_wep_older#68]
Create a pipeline we can use to start integrating `ts_wep` into DM CI.

**Comment by jbkalmbach** [comment]
@tribeiro 

I've come up ideas for three specific tasks to start with that I will add into `ts_wep`. (Information also posted on confluence [here](https://confluence.lsstcorp.org/display/LTS/Gen+3+Pipeline+Development).)

1. Extract Donuts Task
  * Inputs
    * Donut Source Catalog
    * Post-ISR Images
  * Outputs
    * Donut Stamps

2. Estimate Zernike Task
  * Inputs
    * Donut Stamps
  * Outputs
    * Zernike Coefficients

3. Generate Visit Donut Catalog Task
  * Inputs
    * Estimated WCS (from Post-ISR Images?)
    * Reference Catalog
  * Outputs
    * Donut Source Catalog in Pixel X-Y

**Comment by teweitsai** [comment]
I think it might be better to separate the task 3 to two different tasks. One is for the estimated WCS (in normal telescope survey) and one is for post-ISR images (offline analysis).

**Comment by jbkalmbach** [comment]
Closed by #83 , #82 , #80, #78
